// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: leftover.proto

package leftover

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_leftover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	District      string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	State         *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_leftover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopLeft       *Point                 `protobuf:"bytes,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	BottomRight   *Point                 `protobuf:"bytes,2,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_leftover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetTopLeft() *Point {
	if x != nil {
		return x.TopLeft
	}
	return nil
}

func (x *BoundingBox) GetBottomRight() *Point {
	if x != nil {
		return x.BottomRight
	}
	return nil
}

type Leftover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // leftover type e.g. food, electronic...
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Coordiantes   *Point                 `protobuf:"bytes,7,opt,name=coordiantes,proto3" json:"coordiantes,omitempty"`
	Address       *Address               `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leftover) Reset() {
	*x = Leftover{}
	mi := &file_leftover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leftover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leftover) ProtoMessage() {}

func (x *Leftover) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leftover.ProtoReflect.Descriptor instead.
func (*Leftover) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{3}
}

func (x *Leftover) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Leftover) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Leftover) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Leftover) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Leftover) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Leftover) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Leftover) GetCoordiantes() *Point {
	if x != nil {
		return x.Coordiantes
	}
	return nil
}

func (x *Leftover) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type LeftoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Coordinates   *Point                 `protobuf:"bytes,6,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Address       *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftoverRequest) Reset() {
	*x = LeftoverRequest{}
	mi := &file_leftover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftoverRequest) ProtoMessage() {}

func (x *LeftoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftoverRequest.ProtoReflect.Descriptor instead.
func (*LeftoverRequest) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{4}
}

func (x *LeftoverRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *LeftoverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeftoverRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LeftoverRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeftoverRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *LeftoverRequest) GetCoordinates() *Point {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *LeftoverRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type LeftoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Leftover            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftoverResponse) Reset() {
	*x = LeftoverResponse{}
	mi := &file_leftover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftoverResponse) ProtoMessage() {}

func (x *LeftoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftoverResponse.ProtoReflect.Descriptor instead.
func (*LeftoverResponse) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{5}
}

func (x *LeftoverResponse) GetItems() []*Leftover {
	if x != nil {
		return x.Items
	}
	return nil
}

type LeftoverIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftoverIdentity) Reset() {
	*x = LeftoverIdentity{}
	mi := &file_leftover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftoverIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftoverIdentity) ProtoMessage() {}

func (x *LeftoverIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftoverIdentity.ProtoReflect.Descriptor instead.
func (*LeftoverIdentity) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{6}
}

func (x *LeftoverIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_leftover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type LeftoverQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	OwnerId       *string                `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,5,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftoverQuery) Reset() {
	*x = LeftoverQuery{}
	mi := &file_leftover_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftoverQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftoverQuery) ProtoMessage() {}

func (x *LeftoverQuery) ProtoReflect() protoreflect.Message {
	mi := &file_leftover_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftoverQuery.ProtoReflect.Descriptor instead.
func (*LeftoverQuery) Descriptor() ([]byte, []int) {
	return file_leftover_proto_rawDescGZIP(), []int{8}
}

func (x *LeftoverQuery) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *LeftoverQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *LeftoverQuery) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

func (x *LeftoverQuery) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *LeftoverQuery) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

var File_leftover_proto protoreflect.FileDescriptor

const file_leftover_proto_rawDesc = "" +
	"\n" +
	"\x0eleftover.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x05Point\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"\xac\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x00R\x05state\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountryB\b\n" +
	"\x06_state\"[\n" +
	"\vBoundingBox\x12!\n" +
	"\btop_left\x18\x01 \x01(\v2\x06.PointR\atopLeft\x12)\n" +
	"\fbottom_right\x18\x02 \x01(\v2\x06.PointR\vbottomRight\"\xe9\x01\n" +
	"\bLeftover\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bimageUrl\x18\x06 \x01(\tR\bimageUrl\x12(\n" +
	"\vcoordiantes\x18\a \x01(\v2\x06.PointR\vcoordiantes\x12\"\n" +
	"\aaddress\x18\b \x01(\v2\b.AddressR\aaddress\"\xe0\x01\n" +
	"\x0fLeftoverRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bimageUrl\x18\x05 \x01(\tR\bimageUrl\x12(\n" +
	"\vcoordinates\x18\x06 \x01(\v2\x06.PointR\vcoordinates\x12\"\n" +
	"\aaddress\x18\a \x01(\v2\b.AddressR\aaddress\"3\n" +
	"\x10LeftoverResponse\x12\x1f\n" +
	"\x05items\x18\x01 \x03(\v2\t.LeftoverR\x05items\"\"\n" +
	"\x10LeftoverIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"\xbe\x01\n" +
	"\rLeftoverQuery\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\x03 \x01(\tH\x02R\aownerId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x03R\x04type\x88\x01\x01\x12 \n" +
	"\x04bbox\x18\x05 \x01(\v2\f.BoundingBoxR\x04bboxB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\v\n" +
	"\t_owner_idB\a\n" +
	"\x05_type2\xa3\x02\n" +
	"\x0fLeftoverService\x129\n" +
	"\vAddLeftover\x12\x10.LeftoverRequest\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\vGetLeftover\x12\x11.LeftoverIdentity\x1a\t.Leftover\"\x00\x123\n" +
	"\fGetLeftovers\x12\x0e.LeftoverQuery\x1a\x11.LeftoverResponse\"\x00\x125\n" +
	"\x0eUpdateLeftover\x12\t.Leftover\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x0eDeleteLeftover\x12\x0e.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00B\fZ\n" +
	"./leftoverb\x06proto3"

var (
	file_leftover_proto_rawDescOnce sync.Once
	file_leftover_proto_rawDescData []byte
)

func file_leftover_proto_rawDescGZIP() []byte {
	file_leftover_proto_rawDescOnce.Do(func() {
		file_leftover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leftover_proto_rawDesc), len(file_leftover_proto_rawDesc)))
	})
	return file_leftover_proto_rawDescData
}

var file_leftover_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_leftover_proto_goTypes = []any{
	(*Point)(nil),            // 0: Point
	(*Address)(nil),          // 1: Address
	(*BoundingBox)(nil),      // 2: BoundingBox
	(*Leftover)(nil),         // 3: Leftover
	(*LeftoverRequest)(nil),  // 4: LeftoverRequest
	(*LeftoverResponse)(nil), // 5: LeftoverResponse
	(*LeftoverIdentity)(nil), // 6: LeftoverIdentity
	(*DeleteRequest)(nil),    // 7: DeleteRequest
	(*LeftoverQuery)(nil),    // 8: LeftoverQuery
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_leftover_proto_depIdxs = []int32{
	0,  // 0: BoundingBox.top_left:type_name -> Point
	0,  // 1: BoundingBox.bottom_right:type_name -> Point
	0,  // 2: Leftover.coordiantes:type_name -> Point
	1,  // 3: Leftover.address:type_name -> Address
	0,  // 4: LeftoverRequest.coordinates:type_name -> Point
	1,  // 5: LeftoverRequest.address:type_name -> Address
	3,  // 6: LeftoverResponse.items:type_name -> Leftover
	2,  // 7: LeftoverQuery.bbox:type_name -> BoundingBox
	4,  // 8: LeftoverService.AddLeftover:input_type -> LeftoverRequest
	6,  // 9: LeftoverService.GetLeftover:input_type -> LeftoverIdentity
	8,  // 10: LeftoverService.GetLeftovers:input_type -> LeftoverQuery
	3,  // 11: LeftoverService.UpdateLeftover:input_type -> Leftover
	7,  // 12: LeftoverService.DeleteLeftover:input_type -> DeleteRequest
	9,  // 13: LeftoverService.AddLeftover:output_type -> google.protobuf.Empty
	3,  // 14: LeftoverService.GetLeftover:output_type -> Leftover
	5,  // 15: LeftoverService.GetLeftovers:output_type -> LeftoverResponse
	9,  // 16: LeftoverService.UpdateLeftover:output_type -> google.protobuf.Empty
	9,  // 17: LeftoverService.DeleteLeftover:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_leftover_proto_init() }
func file_leftover_proto_init() {
	if File_leftover_proto != nil {
		return
	}
	file_leftover_proto_msgTypes[1].OneofWrappers = []any{}
	file_leftover_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leftover_proto_rawDesc), len(file_leftover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leftover_proto_goTypes,
		DependencyIndexes: file_leftover_proto_depIdxs,
		MessageInfos:      file_leftover_proto_msgTypes,
	}.Build()
	File_leftover_proto = out.File
	file_leftover_proto_goTypes = nil
	file_leftover_proto_depIdxs = nil
}
